
service: serverless-chat

provider:
    name: aws
    runtime: python3.7
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "execute-api:ManageConnections"
        Resource:
          - "arn:aws:execute-api:*:*:**/@connections/*"
      - Effect: Allow
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
          - "dynamodb:UpdateItem"
          - "dynamodb:DeleteItem"
          - "dynamodb:BatchGetItem"
          - "dynamodb:BatchWriteItem"
          - "dynamodb:Scan"
          - "dynamodb:Query"
        Resource:
          - "arn:aws:dynamodb:us-east-1:*:*"

functions:
  connectionManager:
    handler: handler.connection_manager
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultMessage:
    handler: handler.default_message
    events:
      - websocket:
          route: $default
  getRecentMessages:
    handler: handler.get_recent_messages
    events:
      - websocket:
          route: getRecentMessages
  sendMessage:
    handler: handler.send_message
    events:
      - websocket:
          route: sendMessage
  ping:
      handler: handler.ping
      events:
          - http:
              path: ping
              method: get

resources: # CloudFormation template syntax from here on.
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    messagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: messagesTable
          AttributeDefinitions:
              - AttributeName: room
                AttributeType: S
              - AttributeName: messageID
                AttributeType: N
          KeySchema:
              - AttributeName: room
                KeyType: HASH
              - AttributeName: messageID
                KeyType: RANGE
          ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

plugins:
  - serverless-python-requirements
