name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: "@joranbeasley/oas3-shared-editor-client"
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Restore node_modules from cache
      uses: actions/cache@v2
      with:
        path: |
          @joranbeasley/oas3-shared-editor-client/node_modules
          @joranbeasley/oas3-shared-editor-client/*/*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Change To FE directory
      run: pwd
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Create ENV
      run: printf ${{ secrets.PRODUCTION_ENV }} > ./.env.production
    - name: Run build task
      run: yarn build && cp ./.env.production ./build/.env.production
    - name: Copy via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.REMOTE_PORT }}
        key: ${{ secrets.REMOTE_KEY }}
        source: "@joranbeasley/oas3-shared-editor-client/build/*"
        target: ${{ secrets.REMOTE_TARGET }}
