name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: "backend-server[twisted]"
    shell: bash
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7.10]
        poetry-version: [1.1.13]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Poetry install
        run: poetry install
      - name: Poetry install
        run: poetry build
      - name: Copy WHL via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.REMOTE_KEY }}
          source: "backend-server[twisted]"
          target: "~/"
